---
title: "Degree Day Analysis"
author: "Xiaoxuan Yang"
date: "1/11/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


# install.packages("here")
# install.packages("tidyverse")
# install.packages("dplyr")
# install.packages("readxl")
# install.packages("tempdisagg")
# install.packages("zoo")

library("here")
library("tidyverse")
library("readxl")
library("tempdisagg")
library("zoo")

# Set file path
# here::set_here(path = "/Users/xiaoxuanyang/Box Sync/Master Thesis")
here::here()

```


```{r Data Scrapping}
###### NG Residential Sale by States ######

# Download files from EIA website
  URL <- "https://www.eia.gov/dnav/ng/xls/NG_SUM_LSUM_A_EPG0_VRS_MMCF_M.xls"
  download.file(URL, destfile = here("data", "NG_RES.xls"))

  excel_sheets(here("data", "NG_RES.xls")) # read which excel sheet
  NG_Res <- read_excel(here("data", "NG_RES.xls"), 
                       skip = 2, sheet="Data 1")
  NG_Res$Date <- format(as.Date(NG_Res$Date), "%Y-%m") # format year-month
  
##### Electricity Residential Sale by States #####
  # URL <- "https://www.eia.gov/electricity/data/state/sales_annual.xlsx"
  # download.file(URL, destfile = here("data", "Elec_RES.xlsx"))

  
  Elec_Res <- read_xlsx(here("data", "Electricity Monthly Sale.xlsx"))[, 1:6]
  colnames(Elec_Res) <- as.character(unlist(Elec_Res[2,]))
  Elec_Res <- Elec_Res[-c(1:2, 17241),] # units in millions$
  
  Elec_Res$Date <- paste0(Elec_Res$Year,"-", Elec_Res$Month)
  Elec_Res$Date <- as.yearmon(Elec_Res$Date, "%Y-%m")
  Elec_Res$Date <- format(as.Date(Elec_Res$Date), "%Y-%m")
  
  Elec_Res <- Elec_Res %>%
    select(Date, State, Megawatthours) %>%
    spread(State, Megawatthours)
  
  
##### CDD Scrapping #####  
  query_date_CDD <- function(year, month) {
          month<-as.numeric(month)
          monstr <- as.character(month.name[month])
  
  URL<-"ftp://ftp.cpc.ncep.noaa.gov/htdocs/degree_days/weighted/legacy_files/cooling/statesCONUS/"
      download_link<-paste0(URL, year, "/", monstr, ".txt")
      print(download_link)
      temp<-read.table(download_link, skip = c(15),fill = TRUE)
  
 
      temp<-read.table(download_link, skip = c(15),fill = TRUE)
      temp<-temp[-c(59:78),]      #delete unnecessary rows
      temp<-data.frame(lapply(temp, as.character), stringsAsFactors=FALSE)

      # Organizing the headers
      temp[27,1]<-as.character("NEW HAMPSHIRE")
        temp[27,c(2:8)]<- temp[27,c(3:9)]
        temp[27,9]<-temp[28,1]
      temp[29,1]<-as.character("NEW JERSEY")
        temp[29,c(2:8)]<- temp[29,c(3:9)]
        temp[29,9]<-temp[30,1]
      temp[31,1]<-as.character("NEW MEXICO")
        temp[31,c(2:8)]<- temp[31,c(3:9)]
        temp[31,9]<-temp[32,1]
      temp[33,1]<-as.character("NEW YORK")
        temp[33,c(2:8)]<- temp[33,c(3:9)]
        temp[33,9]<-temp[34,1]
      temp[35,1]<-as.character("NORTH CAROLINA")
        temp[35,c(2:8)]<- temp[35,c(3:9)]
        temp[35,9]<-temp[36,1]
      temp[37,1]<-as.character("NORTH DAKOTA")
        temp[37,c(2:8)]<- temp[37,c(3:9)]
        temp[37,9]<-temp[38,1]
      temp[43,1]<-as.character("RHODE ISLAND")
        temp[43,c(2:8)]<- temp[43,c(3:9)]
        temp[43,9]<-temp[44,1]
      temp[45,1]<-as.character("SOUTH CAROLINA")
        temp[45,c(2:8)]<- temp[45,c(3:9)]
        temp[45,9]<-temp[46,1]
      temp[47,1]<-as.character("SOUTH DAKOTA")
        temp[47,c(2:8)]<- temp[47,c(3:9)]
        temp[47,9]<-temp[48,1]
      temp[55,1]<-as.character("WEST VIRGINIA")
        temp[55,c(2:8)]<- temp[55,c(3:9)]
        temp[55,9]<-temp[56,1]
        
        temp.sort <-na.omit(temp)
    
      x <- as.data.frame(t(temp.sort[1:48,2]))
      colnames(x)<-temp.sort[,1]
      return(x)
}
 
  
  Scrape_CDD <- function(startdate, enddate){
    datespan <- seq(from=as.Date(startdate), to=as.Date(enddate), by='months')
    print(paste0("Running scrape CDD: ", startdate, " to ", enddate))
    
    months<- seq(from=datespan[1], to=datespan[length(datespan)],by='months')
    
    y_1 <- as.integer(format(datespan[1], "%Y"))
    m_1 <- as.integer(format(datespan[1], "%m"))
    
    print(paste("Running Scrapping for: Year", y_1, "Month", m_1))
    data_1 <- query_date_CDD(year=y_1,
                         month=m_1)
    
    for (i in seq_along(months)[-1]) {
      y <- as.integer(format(months[i], "%Y"))
      m <- as.integer(format(months[i], "%m"))
      
      print(paste("Running for: Year", y, "Month", m))
      
      data_n <- query_date_CDD(month = m,
                           year = y)
      
      data_1 <- rbind(data_1, data_n)
    }
    data_1[, "Date"] <- datespan
    return(data_1)
  }

CDD <- Scrape_CDD(startdate = "1990-01-01",
                                        enddate = "2018-12-01")
CDD$Date <- format(as.Date(CDD$Date), "%Y-%m")
saveRDS(CDD, here:here("data", "CDD.rds"))



##### HDD Scrapping #####
  query_date_HDD <- function(year, month) {
            month<-as.numeric(month)
            monstr <- as.character(month.name[month])
    
  URL<-"ftp://ftp.cpc.ncep.noaa.gov/htdocs/degree_days/weighted/legacy_files/heating/statesCONUS/"
    download_link<-paste0(URL, year, "/", monstr, ".txt")
    print(download_link)
    temp<-read.table(download_link, skip = c(15),fill = TRUE)
    
   
  temp<-read.table(download_link, skip = c(15),fill = TRUE)
  temp<-temp[-c(59:258),]      #delete unnecessary rows
  temp<-data.frame(lapply(temp, as.character), stringsAsFactors=FALSE)
  
  # Organizing the headers
  temp[27,1]<-as.character("NEW HAMPSHIRE")
    temp[27,c(2:8)]<- temp[27,c(3:9)]
    temp[27,9]<-temp[28,1]
  temp[29,1]<-as.character("NEW JERSEY")
    temp[29,c(2:8)]<- temp[29,c(3:9)]
    temp[29,9]<-temp[30,1]
  temp[31,1]<-as.character("NEW MEXICO")
    temp[31,c(2:8)]<- temp[31,c(3:9)]
    temp[31,9]<-temp[32,1]
  temp[33,1]<-as.character("NEW YORK")
    temp[33,c(2:8)]<- temp[33,c(3:9)]
    temp[33,9]<-temp[34,1]
  temp[35,1]<-as.character("NORTH CAROLINA")
    temp[35,c(2:8)]<- temp[35,c(3:9)]
    temp[35,9]<-temp[36,1]
  temp[37,1]<-as.character("NORTH DAKOTA")
    temp[37,c(2:8)]<- temp[37,c(3:9)]
    temp[37,9]<-temp[38,1]
  temp[43,1]<-as.character("RHODE ISLAND")
    temp[43,c(2:8)]<- temp[43,c(3:9)]
    temp[43,9]<-temp[44,1]
  temp[45,1]<-as.character("SOUTH CAROLINA")
    temp[45,c(2:8)]<- temp[45,c(3:9)]
    temp[45,9]<-temp[46,1]
  temp[47,1]<-as.character("SOUTH DAKOTA")
    temp[47,c(2:8)]<- temp[47,c(3:9)]
    temp[47,9]<-temp[48,1]
  temp[55,1]<-as.character("WEST VIRGINIA")
    temp[55,c(2:8)]<- temp[55,c(3:9)]
    temp[55,9]<-temp[56,1]
    
    temp.sort <-na.omit(temp)
  
    x <- as.data.frame(t(temp.sort[1:48,2]))
    colnames(x)<-temp.sort[,1]
    return(x)
  }
    
  # Scraping function
  
      Scrape_HDD <- function(startdate, enddate){
        datespan <- seq(from=as.Date(startdate), to=as.Date(enddate), by='months')
        print(paste0("Running scrape HDD: ", startdate, " to ", enddate))
        
        months<- seq(from=datespan[1], to=datespan[length(datespan)],by='months')
        
        y_1 <- as.integer(format(datespan[1], "%Y"))
        m_1 <- as.integer(format(datespan[1], "%m"))
        
        print(paste("Running for: Year", y_1, "Month", m_1))
        data_1 <- query_date_HDD(year=y_1,
                             month=m_1)
        
        for (i in seq_along(months)[-1]) {
          y <- as.integer(format(months[i], "%Y"))
          m <- as.integer(format(months[i], "%m"))
          
          print(paste("Running for: Year", y, "Month", m))
          
          data_n <- query_date_HDD(month = m,
                               year = y)
          
          data_1 <- rbind(data_1, data_n)
        }
        data_1[, "Date"] <- datespan
        return(data_1)
      }
    
    HDD<-Scrape_HDD(startdate = "1990-01-01",
                                            enddate = "2018-12-01")

    saveRDS(HDD, here:here("data", "HDD.rds"))
   
    
    
    
##### Load GDP (chained 2009 dollar) #####
    GDP <- read_xlsx(here("data", "Real GDP 1990-2017 (chained 2009 dollar).xlsx"))
    GDP <- as.data.frame(t(GDP)) # switch row and column
    colnames(GDP) <- as.character(unlist(GDP[1,]))
    GDP = GDP[-1,] # units in millions$

    
##### Interpolate Residential Population #####
    # Load an indicator series
    pop_US_mon<-read_xlsx(here("data", "US Monthly Population.xlsx"))[,2]
    us.m<-ts(pop_US_mon, frequency = 12, start = c(1990))
    
    
    # Read Annual State Population
    pop_annual<-read.csv(here("data", "State Annual Population.csv"))
    state.a<-ts(pop_annual, frequency = 1, start=c(1990))
    
    # Interpolate according to the annual data
    state.m<-predict(td(state.a~us.m, conversion="average"))
    
    saveRDS(state.m, here("data","state_monthly_pop.rds"))
        
    
  
    
```


```{r}

```

