---
title: "Regression Analysis"
author: "Xiaoxuan Yang"
date: "1/18/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# 
# install.packages("here")
# install.packages("tidyverse")
# install.packages("dplyr")
# install.packages("tibble")
# install.packages("readxl")
# install.packages("tempdisagg")
# install.packages("zoo")
# install.packages("devtools")
# devtools::install_github("xjessiex/envutils")
# install.packages("processx")
# install.packages("colorspace")
# install.packages("lfe")
# install.packages("data.table")
# install.packages("tseries")
# install.packages("lmtest")

library("lmtest")
library("processx")
library("colorspace")
library("here")
library("tidyverse")
library("readxl")
library("tempdisagg")
library("zoo")
library("envutils") # for scrapping
library("lfe")
library("data.table")
library("tseries")
library("datasets")
library("DT")


# Set file path with here()
# setwd("/Users/Jessie Yang/Box Sync/Master Thesis")
# set_here(path = "C:/Users/xy77/Box Sync/Master Thesis")
here::here()

```

```{r Load state profiles}
# get filenames for all 48 states
  list.filesnames<-list.files(here("state"), pattern=".csv")
  list.data<-list() # create a list
 
```

```{r Compile all states}
  # create a dataframe
    df<-as.data.frame(matrix(ncol=8, nrow=0))

  # go through each state
    for (i in 1:length(list.filesnames)){
      
    # add statename as a column
    statename<-substr(list.filesnames[i],1,nchar(list.filesnames[i])-4)
    list.filesnames[i]<-substr(list.filesnames[i],1,nchar(list.filesnames[i])-4)
    
    
    # load data for each state
    data <- read.csv(here("state", paste0(statename, ".csv")))
    
    # Organize statenames
    snames <- state.name[-c(2,11)]
    
    data[,"State"] = rep(snames[i], nrow(data))
    df<-rbind(df, data)
    }
   
    saveRDS(list.filesnames, here("data", "statename.rds"))

    
  # convert date from factor to date
    df$Date <- as.yearmon(df$Date, "%Y-%m")
    df$Date <- as.Date(df$Date)
    df[, "Year"] <- substring(df$Date,1,4)

  # define column names for the compiled file
     colnames(df)<-c(
       "Index",
       "Date", 
       "Real GDP (millions of chained 2012 dollars) per capita",
       "Electricity Sale to Residential Consumers per capita (MJ/person)", 
       "Natural Gas Deliveries to Residential Consumers per capita (MJ/person)", 
       "HDD",
       "CDD",
       "DD",
       "State",
       "Year")
     
     saveRDS(df, here("data", "all_state.rds"))
```

```{r Make regression with all states}
data <- readRDS(here("data", "all_state.rds"))
statename <- readRDS(here("data", "statename.rds"))

colnames(data)<-c(
       "Index",
       "Date", 
       "GDPpc",
       "Elecrespc", 
       "NGrespc", 
       "HDD",
       "CDD",
       "DD",
       "State",
       "Year")


##### General lm for all states #####
  lm_fit <- lm(Elecrespc ~ DD + GDPpc, data)
  summary(lm_fit)$r.squared

  plot(lm_fit)

##### Elec: State and Year fixed effects #####
  fedata <- data
  fedata$Year <- as.factor(fedata$Year)
  fedata$State <- as.factor(fedata$State)
  fedata[, "DD2"] <- fedata$DD^2
   
  lm_felm <- felm(fedata$Elecrespc ~ fedata$DD + fedata$DD2 + fedata$GDP | fedata$Year + fedata$State)
  
  summary(lm_felm)


  
##### NG: State and Year fixed effects #####
  fngdata <- data
  fngdata$Year <- as.factor(fngdata$Year)
  fngdata$State <- as.factor(fngdata$State)
  fngdata[, "DD2"] <- fngdata$DD^2
   
  lm_fnglm <- felm(fngdata$NGrespc ~ fngdata$DD + fngdata$DD2 + fngdata$GDP | fngdata$Year + fngdata$State)

  summary(lm_fnglm)
  

```


```{r Make regression for yearly values and abstract characteristics of the curve}
  # Load all state files  
    data <- readRDS(here("data", "all_state.rds"))
  # Load statenames
    snames <- state.name[-c(2,11)]

  # Create a df to collect regression information
    df<-as.data.frame(matrix(ncol=5, nrow=0))
    
##### Elec: Annual regression #####
    type = "Electricity"
  for (i in 1:length(snames)){

    
    statename <-snames[i]
    statedata <- filter(data, State == statename)
    
    for (j in 1990:2017){

      yeardata <- filter(statedata, Year == j)
      # Edit column     
        colnames(yeardata)<-c(
             "Index",
             "Date", 
             "GDPpc",
             "Elecrespc", 
             "NGrespc", 
             "HDD",
             "CDD",
             "DD",
             "State",
             "Year")
      
 
        yfit <- lm(Elecrespc ~ DD + I(DD^2),
                   data = yeardata)
        
      # Collect information
        a = yfit$coefficients[3]
        b = yfit$coefficients[2]
        c = yfit$coefficients[1]

      # Collect DDmin@Elecmin and Elecmin from the model
        DDmin= as.numeric(seq(min(yeardata$DD), 
                            max(yeardata$DD))
                        [which.min(predict(yfit, newdata = data.frame(DD = seq(min(yeardata$DD), 
                                                                               max(yeardata$DD)))))])
        
        df<-rbindlist(list(df, 
                           as.list(c(as.character(statename), j, "DD at lowest electricity consumption", type, DDmin))))

        Elecmin = min(yfit$fitted.values)

        df<-rbindlist(list(df, 
                           as.list(c(as.character(statename), j, "Lowest electricity consumption", type, Elecmin))))


      # Collect curvature
        k = 2*a

        df<-rbindlist(list(df, 
                           as.list(c(as.character(statename), j, "Curvature", type, k))))

      # Collect extreme values
      # Elec @ DDmin
      DDmin = min(yeardata$DD)
      Elec_DDmin = a*DDmin^2+b*DDmin+c
      df<-rbindlist(list(df, 
                         as.list(c(as.character(statename), j, "Electricity consumption at lowest DD", type, Elec_DDmin))))
      df<-rbindlist(list(df,
                         as.list(c(as.character(statename), j, "DDmin", type, DDmin))))
      
      # Elec @ DDmax
      DDmax = max(yeardata$DD)
      Elec_DDmax = a*DDmax^2+b*DDmax+c
      df<-rbindlist(list(df, 
                         as.list(c(as.character(statename), j, "Electricity consumption at highest DD", type, Elec_DDmax))))
      df<-rbindlist(list(df,
                         as.list(c(as.character(statename), j, "DDmax", type, DDmax))))

      
      }
    }
    
    colnames(df)<-c("State", "Year", "Measurement", "Energy Type", "Value")

    saveRDS(df, here("data", "Electricity Regression Summary.rds"))
    
    write.csv(df, here("data", "Electricity Regression Summary.csv"))
    
    
##### NG: Annual regression #####
    df <-as.data.frame(matrix(ncol=5, nrow=0))
    type = "Natural Gas"
  
  for (i in 1:length(snames)){
    statedata <- filter(data, State == statename)
    statename <-snames[i]
    
  for (j in 1990:2017){
    yeardata <- filter(statedata, Year == j)
    
      
      # Edit column     
        colnames(yeardata)<-c(
             "Index",
             "Date", 
             "GDPpc",
             "Elecrespc", 
             "NGrespc", 
             "HDD",
             "CDD",
             "DD",
             "State",
             "Year")
        
        
        
        yfit <- lm(NGrespc ~ 
                     DD + I(DD^2),
                     data=yeardata)
        
        
      # Collect information
        a = yfit$coefficients[3]
        b = yfit$coefficients[2]
        c = yfit$coefficients[1]
        
      # Collect DDmin and Elecmin from the model
        DDmin= as.numeric(seq(min(yeardata$DD), 
                            max(yeardata$DD))
                        [which.min(predict(yfit, newdata = data.frame(DD = seq(min(yeardata$DD), 
                                                                               max(yeardata$DD)))))])
        
        df<-rbindlist(list(df, as.list(c(as.character(statename), j, "DD at lowest NG consumption", type, DDmin))))
      
        NGmin = min(yfit$fitted.values)
        
        df<-rbindlist(list(df, as.list(c(as.character(statename), j, "Lowest NG consumption", type, NGmin))))
  
  
      # Collect curvature
        k = 2*a
        
        df<-rbindlist(list(df, as.list(c(as.character(statename), j, "Curvature", type, k))))
  
      # Collect extreme values
        # Elec @ DDmin
        DDmin = min(yeardata$DD)
        NG_DDmin = a*DDmin^2+b*DDmin+c
        df<-rbindlist(list(df, as.list(c(as.character(statename), j, "NG consumption at lowest DD", type, NG_DDmin))))
        
        df<-rbindlist(list(df,
                         as.list(c(as.character(statename), j, "DDmin", type, DDmin))))
    
        # Elec @ DDmax
        DDmax = max(yeardata$DD)
        NG_DDmax = a*DDmax^2+b*DDmax+c
        df<-rbindlist(list(df, 
                           as.list(c(as.character(statename), j, "NG consumption at highest DD", type, NG_DDmax))))
        df<-rbindlist(list(df,
                           as.list(c(as.character(statename), j, "DDmax", type, DDmax))))
 
       
      }
    }
    colnames(df)<-c("State", "Year", "Measurement", "Energy Type", "Value")

    saveRDS(df, here("data", "NG Regression Summary.rds"))
    
    write.csv(df, here("data", "NG Regression Summary.csv"))
    
```


```{r Residual Tests}

 # Load all state files  
    data <- readRDS(here("data", "all_state.rds"))
  # Load statenames
    snames <- state.name[-c(2,11)]
    
  # test 
    test <- as.data.frame(matrix(ncol=4, nrow=0))
##### Elec: Annual regression #####
    type = "Electricity"
  for (i in 1:length(snames)){
  
    statename <- snames[i]
    statedata <- filter(data, State == statename)
    
    for (j in 1990:2017){
      
      yeardata <- filter(statedata, Year == j)
      # Edit column     
        colnames(yeardata)<-c(
             "Index",
             "Date", 
             "GDPpc",
             "Elecrespc", 
             "NGrespc", 
             "HDD",
             "CDD",
             "DD",
             "State",
             "Year")
      

    
        yfit <- lm(Elecrespc ~ 
                     DD + I(DD^2)+ GDPpc,
                     data=yeardata)
        
        # Check violation of independence 
        # DW stats should be between 0.449 and 1.575 (Savin and White)
        library(car)
        dwtest <- durbinWatsonTest(yfit$residuals) 
        
        # # Check homoscedasticity
        # par(mfrow=c(2,2)) # init 4 charts in 1 panel
        # plot(yfit)
        bptest <- lmtest::bptest(yfit)$p.value
        
        plot(yfit$residuals)
      
        # Possible tests
        # boxtest <- Box.test(yfit$residuals, type = c("Ljung-Box"))$p.value
        # adftest <- adf.test(yfit$residuals)$p.value
        # kpsstest <- kpss.test(yfit$residuals)$p.value
        
      
        # test <- rbindlist(list(test, as.list(c(as.character(statename), j, "Ljung Box", boxtest))))
        # test <- rbindlist(list(test, as.list(c(as.character(statename), j, "ADF", adftest))))
        test <- rbindlist(list(test, as.list(c(as.character(statename), j, "bptest", bptest))))
        test <- rbindlist(list(test, as.list(c(as.character(statename), j, "DWtest", dwtest))))

     
      }
    }

```


```{r Combine quadratic summary}
elec <- readRDS(here("data", "elec regression summary.rds"))
NG <- readRDS(here("data", "NG regression summary.rds"))

quadratic_all <- rbind(elec, NG)

saveRDS(quadratic_all, here("data", "all regression summary.rds"))
```


```{r Curve characteristics}
##### Electricity curve #####

# Create a file to store data
  elecdf <- as.data.frame(matrix(ncol=5, nrow=0)) #col: state, energy type, characteristics, slope, p value


# Load electricity regression summary
  elecreg <- readRDS(here("data", "Electricity Regression Summary.rds"))

  colnames(elecreg) <- c("state", "year", "measurement", "energytype", "value")

# Load statenames
    snames <- state.name[-c(2,11)]

for (i in 1:48){

  statename <- snames[i]
  
  # filter statedate
  statedata <- subset(elecreg, state == statename)
  statedata$year <- as.numeric(statedata$year)
  
  # regress DD
  DD_lowelec <- subset(statedata, measurement == "DD at lowest electricity consumption")
  lm_fit1 <- lm(value ~ year, 
                      data = DD_lowelec)
  elecdf<-rbindlist(list(elecdf, as.list(c(as.character(statename),
                                     "electricity",
                                     "DD at lowest energy use", 
                                     as.numeric(coefficients(lm_fit1)[2]), 
                                     as.numeric(summary(lm_fit1)$coefficients[2,4]) ))))
  
  
  lowelec <- subset(statedata, measurement == "Lowest electricity consumption")
  lm_fit2 <- lm(value ~ year, 
                      data = lowelec)
  elecdf<-rbindlist(list(elecdf, as.list(c(as.character(statename),
                                     "electricity",
                                     "lowest energy use", 
                                     as.numeric(coefficients(lm_fit2)[2]), 
                                     as.numeric(summary(lm_fit2)$coefficients[2,4]) ))))
  
  curvature <- subset(statedata, measurement == "Curvature")
  lm_fit3 <- lm(value ~ year, 
                      data = curvature)
  elecdf<-rbindlist(list(elecdf, as.list(c(as.character(statename),
                                     "electricity",
                                     "curvature", 
                                     as.numeric(coefficients(lm_fit3)[2]), 
                                     as.numeric(summary(lm_fit3)$coefficients[2,4]) ))))
  
  lowDD <- subset(statedata, measurement == "Electricity consumption at lowest DD")
  lm_fit4 <- lm(value ~ year, 
                      data = lowDD)
  elecdf<-rbindlist(list(elecdf, as.list(c(as.character(statename),
                                     "electricity",
                                     "energy use at lowest DD", 
                                     as.numeric(coefficients(lm_fit4)[2]), 
                                     as.numeric(summary(lm_fit4)$coefficients[2,4]) ))))
  
  DDmin <- subset(statedata, measurement == "DDmin")
  lm_fit5 <- lm(value ~ year, 
                      data = DDmin)
  elecdf<-rbindlist(list(elecdf, as.list(c(as.character(statename),
                                     "electricity",
                                     "DDmin", 
                                     as.numeric(coefficients(lm_fit5)[2]), 
                                     as.numeric(summary(lm_fit5)$coefficients[2,4]) ))))
  
  highDD <- subset(statedata, measurement == "Electricity consumption at highest DD")
  lm_fit6 <- lm(value ~ year, 
                      data = highDD)
  elecdf<-rbindlist(list(elecdf, as.list(c(as.character(statename),
                                     "electricity",
                                     "energy use at highest DD", 
                                     as.numeric(coefficients(lm_fit6)[2]), 
                                     as.numeric(summary(lm_fit6)$coefficients[2,4]) ))))
  
  DDmax <- subset(statedata, measurement == "DDmax")
  lm_fit7 <- lm(value ~ year, 
                      data = DDmax)
  elecdf<-rbindlist(list(elecdf, as.list(c(as.character(statename),
                                     "electricity",
                                     "DDmax", 
                                     as.numeric(coefficients(lm_fit7)[2]), 
                                     as.numeric(summary(lm_fit7)$coefficients[2,4]) ))))

}
    colnames(elecdf) <- c("state", "energy type", "characteristics", "slope", "pvalue")
    
    
    # add pvalue table
    elecdf2 <- elecdf[, c(1,2,3,5)]
    pvalue_elec <- elecdf2 %>%
    spread(`characteristics`, `pvalue`)
  
    datatable(pvalue_elec) %>%
    formatStyle(
      3:9, 
      backgroundColor = styleInterval(c(0.05), c("orange", "grey"))
    )
    
    # add slope table
    elecdf3 <- elecdf[, c(1,2,3,4)]
    slope_elec <- elecdf3 %>%
    spread(`characteristics`, `slope`)
  
    datatable(slope_elec) %>%
    formatStyle(
      3:9, 
      backgroundColor = styleInterval(c(0.05), c("orange", "grey"))
    )
    
    write.csv(slope_elec, here("data", "electricity curve slope.csv"))

    write.csv(pvalue_elec, here("data", "electricity curve pvalue.csv"))
    
    saveRDS(elecdf, here("data", "Electricity Curve Summary.rds"))
    

##### NG curve #####

# Create a file to store data
  NGdf <- as.data.frame(matrix(ncol=5, nrow=0)) #col: state, energy type, characteristics, slope, p value


# Load electricity regression summary
  NGreg <- readRDS(here("data", "NG Regression Summary.rds"))

  colnames(NGreg) <- c("state", "year", "measurement", "energytype", "value")

# Load statenames
    snames <- state.name[-c(2,11)]

for (i in 1:48){

  statename <- snames[i]
  
  # filter statedate
  statedata <- subset(NGreg, state == statename)
  statedata$year <- as.numeric(statedata$year)
  
  # regress DD
  DD_lowNG <- subset(statedata, measurement == "DD at lowest NG consumption")
  lm_fit1 <- lm(value ~ year, 
                      data = DD_lowNG)
  NGdf<-rbindlist(list(NGdf, as.list(c(as.character(statename),
                                     "NG",
                                     "DD at lowest energy use", 
                                     as.numeric(coefficients(lm_fit1)[2]), 
                                     as.numeric(summary(lm_fit1)$coefficients[2,4]) ))))
  
  
  lowNG <- subset(statedata, measurement == "Lowest NG consumption")
  lm_fit2 <- lm(value ~ year, 
                      data = lowNG)
  NGdf<-rbindlist(list(NGdf, as.list(c(as.character(statename),
                                     "NG",
                                     "lowest energy use", 
                                     as.numeric(coefficients(lm_fit2)[2]), 
                                     as.numeric(summary(lm_fit2)$coefficients[2,4]) ))))
  
  curvature <- subset(statedata, measurement == "Curvature")
  lm_fit3 <- lm(value ~ year, 
                      data = curvature)
  NGdf<-rbindlist(list(NGdf, as.list(c(as.character(statename),
                                     "NG",
                                     "curvature", 
                                     as.numeric(coefficients(lm_fit3)[2]), 
                                     as.numeric(summary(lm_fit3)$coefficients[2,4]) ))))
  
  lowDD <- subset(statedata, measurement == "NG consumption at lowest DD")
  lm_fit4 <- lm(value ~ year, 
                      data = lowDD)
  NGdf<-rbindlist(list(NGdf, as.list(c(as.character(statename),
                                     "NG",
                                     "energy use at lowest DD", 
                                     as.numeric(coefficients(lm_fit4)[2]), 
                                     as.numeric(summary(lm_fit4)$coefficients[2,4]) ))))
  
  DDmin <- subset(statedata, measurement == "DDmin")
  lm_fit5 <- lm(value ~ year, 
                      data = DDmin)
  NGdf<-rbindlist(list(NGdf, as.list(c(as.character(statename),
                                     "NG",
                                     "DDmin", 
                                     as.numeric(coefficients(lm_fit5)[2]), 
                                     as.numeric(summary(lm_fit5)$coefficients[2,4]) ))))
  
  highDD <- subset(statedata, measurement == "NG consumption at highest DD")
  lm_fit6 <- lm(value ~ year, 
                      data = highDD)
  NGdf<-rbindlist(list(NGdf, as.list(c(as.character(statename),
                                     "NG",
                                     "energy use at highest DD", 
                                     as.numeric(coefficients(lm_fit6)[2]), 
                                     as.numeric(summary(lm_fit6)$coefficients[2,4]) ))))
  
  DDmax <- subset(statedata, measurement == "DDmax")
  lm_fit7 <- lm(value ~ year, 
                      data = DDmax)
  NGdf<-rbindlist(list(NGdf, as.list(c(as.character(statename),
                                     "NG",
                                     "DDmax", 
                                     as.numeric(coefficients(lm_fit7)[2]), 
                                     as.numeric(summary(lm_fit7)$coefficients[2,4]) ))))

}
  
  
  
    colnames(NGdf) <- c("state", "energy type", "characteristics", "slope", "pvalue")
    
    
    # add pvalue table
    NGdf2 <- NGdf[, c(1,2,3,5)]
    pvalue_NG <- NGdf2 %>%
    spread(`characteristics`, `pvalue`)
  
    datatable(pvalue_NG) %>%
    formatStyle(
      3:9, 
      backgroundColor = styleInterval(c(0.05), c("orange", "grey"))
    )
    
    # add slope table
    NGdf3 <- NGdf[, c(1,2,3,4)]
    slope_NG <- NGdf3 %>%
    spread(`characteristics`, `slope`)
  
    datatable(slope_NG) %>%
    formatStyle(
      3:9, 
      backgroundColor = styleInterval(c(0.05), c("orange", "grey"))
    )
    
    
    
    write.csv(pvalue_NG, here("data", "NG curve pvalue.csv"))
    write.csv(slope_NG, here("data", "NG curve slope.csv"))

    saveRDS(NGdf, here("data", "NG Curve Summary.rds"))
        
    
    compile <- rbind(elecdf, NGdf)
    write.csv(compile, here("data", "Curve Summary.csv"))
```



